---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-cluster-role-binding
subjects:
  - kind: User
    name: common-fate-admin
  - kind: ServiceAccount
    name: commonfate-service-account
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-cluster-role-binding
subjects:
  - kind: User
    name: common-fate-readonly
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
