---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-cluster-role-binding
  labels: {{- include "worker-helm.labels" . | nindent 4 }}
subjects:
  - kind: User
    name: common-fate-admin
roleRef:
  kind: ClusterRole
  name: common-fate-admin-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-cluster-role-binding
  labels: {{- include "worker-helm.labels" . | nindent 4 }}
subjects:
  - kind: User
    name: common-fate-readonly
roleRef:
  kind: ClusterRole
  name: common-fate-readonly-role
  apiGroup: rbac.authorization.k8s.io
